# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    ../../../modules/mixed/nix
    # Include the results of the hardware scan.
    ./hardware-configuration.nix
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  swapDevices = [{ 
    device = "/swapfile"; 
    size = 32*1024; # Creates an 32GB swap file 
  }];

  programs.nix-index-database.comma.enable = true;

  # boot.kernelPackages = pkgs.linuxPackages_zen;

  networking.hostName = "walter"; # Define your hostname.
  networking.nameservers = [ "8.8.8.8" "1.1.1.1" ];
  networking.useDHCP = false;
  networking.dhcpcd.enable = false;
  networking.networkmanager.enable = true;
  services.resolved = {
  enable = false;  
  domains = [ "~." ];
};
  #environment.etc."resolv.conf".text = ''
    # Generated by environment.etc (NixOS static DNS fix)
 #   nameserver 8.8.8.8
#    nameserver 1.1.1.1
 #   # Trust the AD (authentic data) flag and use EDNS(0)
 #   options trust-ad edns0
#  '';

  time.timeZone = "Europe/Moscow";

  programs.proxychains = {
    enable = true;
    package = pkgs.proxychains-ng;
    proxies = {
      local = {
        enable = true;
        type = "socks5";
        host = "127.0.0.1";
        port = 1080;
      };
    };
  };

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  services.xserver.videoDrivers = ["nvidia"];
  hardware.nvidia = {
    modesetting.enable = true;
    open = true;
    nvidiaSettings = false;
    nvidiaPersistenced = true;
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };
  programs.uwsm = {
    enable =true;
  };
  services.displayManager.ly.enable = true;
  programs.hyprland = {
    enable = true;
    withUWSM = true;
  };

  programs.steam = {
    enable = true;
    protontricks.enable = true;
    gamescopeSession.enable = true;
  };
  services.sunshine = {
    enable = true;
    autoStart = true;
    capSysAdmin = true;
    openFirewall = true;
  };

  users.users.phygson = {
    isNormalUser = true;
    extraGroups = ["wheel"];
  };

  users.users.ss = {
    isNormalUser = true;
    extraGroups = ["wheel"];
  };

  programs.firefox.enable = true;
  programs.fish.enable = true;
  services.flatpak.enable = true;

  environment.systemPackages = with pkgs; [
    neovim
    kitty
    git
    shadowsocks-libev
    ckan
    lutris
    prismlauncher
    qbittorrent
    distrobox
    polkit_gnome
    inputs.comfyui-nix.packages.${pkgs.stdenv.hostPlatform.system}.cuda
    libreoffice-fresh
    hunspell
    hunspellDicts.ru_RU
  ];

  systemd.user.services.polkit-gnome-authentication-agent-1 = {
  description = "polkit-gnome-authentication-agent-1";
  wantedBy = [ "graphical-session.target" ];
  wants = [ "graphical-session.target" ];
  after = [ "graphical-session.target" ];
  serviceConfig = {
    Type = "simple";
    ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
    Restart = "on-failure";
    RestartSec = 1;
    TimeoutStopSec = 10;
  };
};

  services.mihomo = {
    enable = true;
    tunMode=true;
    configFile = "/home/phygson/.config/mihomo/config.yaml";
  };

  programs.nh = {
    enable = true;
    clean.enable = true;
    clean.extraArgs = "--keep-since 4d --keep 3";
    flake = "/etc/nixos/tumor"; # sets NH_OS_FLAKE variable for you
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  networking.firewall = let ports = [ 80 443 1080 9977 9978 27015 27036 ]; in {
    enable = false;
    allowedUDPPorts = ports;
    allowedTCPPorts = ports ++ [ 27031 27032 27033 27034 27035 ];
  };
  security.polkit.enable = true;

  system.stateVersion = "26.05";
}
