# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/walter";
    fsType = "btrfs";
    options = ["subvol=@nixos" "compress=zstd" "noatime"];
  };

  boot.initrd.luks.devices."walter".device = "/dev/disk/by-uuid/be0430cb-1302-410e-967f-dab8d3c126a4";

  fileSystems."/home" = {
    device = "/dev/mapper/walter";
    fsType = "btrfs";
    options = ["subvol=@nixos_home" "compress=zstd" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/walter";
    fsType = "btrfs";
    options = ["subvol=@nixos_store" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/56FC-6EF0";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
