# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/heart";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "space_cache=v2"];
  };

  boot.initrd.luks.devices."heart".device = "/dev/disk/by-uuid/6fda77c2-6fee-4d9f-b29e-a56625d8cf8b";

  fileSystems."/home" = {
    device = "/dev/mapper/heart";
    fsType = "btrfs";
    options = ["subvol=@home" "space_cache=v2" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/heart";
    fsType = "btrfs";
    options = ["subvol=@nix" "space_cache=v2" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EAA9-3897";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/smth" = {
    device = "/dev/disk/by-label/smth";
    fsType = "btrfs";
    options = [ "subvol=@" "noatime" "compress=zstd:1" "discard=async" ];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
